CREATE DATABASE Projeto

CREATE TABLE Usuario 
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Senha VARCHAR(MAX) NOT NULL,
	Ativo BIT NOT NULL,
	DataCadastro DATETIME NOT NULL,
	DataAlteracao DATETIME NULL
)

